---
deployment:
  tasks:
    - export DEPLOYPATH=/home/Ysgvihssc/public_html
    
    - /bin/cp -R * $DEPLOYPATH
    
    - if [ ! -f $DEPLOYPATH/.env ]; then /bin/cp $DEPLOYPATH/.env.example $DEPLOYPATH/.env; fi
    
    - cd $DEPLOYPATH
    
    - composer install --no-dev --optimize-autoloader --no-interaction
    
    - php artisan config:clear
    - php artisan route:clear
    - php artisan view:clear
    - php artisan cache:clear
    
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache
    
    - php artisan storage:link
    
    - chmod -R 755 storage
    - chmod -R 755 bootstrap/cache
    
    - chmod -R 755 storage/app
    - chmod -R 755 storage/framework
    - chmod -R 755 storage/logs
